import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "./components/Navbar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       
       <div
          id="transition-overlay"
          style={{
            position: "fixed",
            inset: 0,
            background: "black",
            opacity: 0,
            pointerEvents: "none",
            zIndex: -1, // Behind everything by default
            transition: "z-index 0s", // Instant z-index change
          }}
        />
        {children}
      </body>
      
    </html>
  );
}
