const events = [
  {
    'cat': 'LITERARY EVENTS',
    'events': [['EWM', 'ESSAY WRITING MALAYALAM'], ['EWE', 'ESSAY WRITING ENGLISH'], ['EWH', 'ESSAY WRITING HINDI'], ['PWM', 'POETRY WRITING MALAYALAM'], ['PWE', 'POETRY WRITING ENGLISH'], ['PWH', 'POETRY WRITING HINDI'], ['SSM', 'SHORT STORY MALAYALAM'], ['SSE', 'SHORT STORY ENGLISH'], ['SSH', 'SHORT STORY HINDI'], ['EM', 'ELOCUTION MALAYALAM'], ['EH', 'ELOCUTION HINDI'], ['EE', 'ELOCUTION ENGLISH'], ['RM', 'RECITATION MALAYALAM'], ['RE', 'RECITATION ENGLISH'], ['RH', 'RECITATION HINDI'], ['QZ', 'QUIZ'], ['FRM', 'FILM REVIEW MALAYALAM'], ['FRE', 'FILM REVIEW ENGLISH'], ['DE', 'DEBATE ENGLISH'], ['DM', 'DEBATE MALAYALAM'], ['DH', 'DEBATE HINDI']]
  },
  {
    'cat': 'FINE ARTS',
    'events': [['POC', 'PAINTING OIL COLOR'], ['PWC', 'PAINTING WATERCOLOR'], ['PND', 'PENCIL DRAWING'], ['POD', 'POSTER DESIGN'], ['COO', 'CARTOONING'], ['PG', 'PHOTOGRAPHY'], ['CRC', 'CARICATURE'], ['RG', 'RANGOLI'], ['CLG', 'COLLAGE'], ['MH', 'MEHNDI'], ['FP', 'FACE PAINTING '],]
  },
  {
    'cat': 'MUSIC',
    'events': [['LM', 'LIGHT MUSIC MALE'], ['LF', 'LIGHT MUSIC FEMALE'], ['CM', 'CLASSICAL MUSIC'], ['WSS', 'WESTERN SONG SOLO'], ['PE', 'INSTRUMENTAL PERCUSSION EASTERN'], ['PW', 'INSTRUMENTAL PERCUSSION WESTERN'], ['EW', 'INSTRUMENTAL NON PERCUSSION WIND EASTERN'], ['WW', 'INSTRUMENTAL NON PERCUSSION WIND WESTERN'], ['ES', 'INSTRUMENTAL NON PERCUSSION STRING EASTERN'], ['WS', 'INSTRUMENTAL NON PERCUSSION STRING WESTERN'], ['GM', 'EASTERN GROUP MUSIC'], ['WG', 'WESTERN GROUP SONG'], ['GA', 'GANAMELA'], ['MA', 'MAPPILAPATTU'], ['NA', 'NADANPATTU'], ['PS', 'PATRIOTIC SONG'], ['VAN', 'VANJIPATTU '],]
  },
  {
    'cat': 'DANCE',
    'events': [['SD', 'SOLO DANCE FOLK'], ['AT', 'ADAPT TUNE'], ['VP', 'VATTAPPATU'], ['OF', 'OPPANA FEMALE'], ['KK', 'KOLKALI'], ['TH', 'THIRUVATHIRA'], ['SS', 'STEP IN SYNCHRO'], ['VC', 'VIDEO CHOREOGRAPHY'], ['NO', 'NOSTALGIA'], ['WD', 'WESTERN GROUP DANCE'], ['GD', 'EASTERN GROUP DANCE'], ['MOH', 'MOHINIYATTAM'], ['BM', 'BHARATHANATTYAM (M)'], ['BF', 'BHARATHANATTYAM (F)'], ['KPF', 'KUCHIPPUDI (F)'], ['KPM', 'KUCHIPPUDI (M)'], ['MGK', 'MARGAMKALI'], ['FU', 'FUSION'], ['DFF', 'DUFFMUTTU']]
  },
  {
    'cat': 'THEATRE',
    'events': [['MT', 'MONO ACT'], ['MY', 'MIMICRY'], ['MI', 'MIME'], ['SK', 'SKIT'], ['KP', 'KATHAPRASANGM'], ['D', 'DRAMA'], ['FAD', 'FANCY DRESS'], ['R', 'RAMP']]
  }

]

export default events